#!/usr/bin/env python3
"""Digest votes into config/interests.md — in plain English, on purpose.

He rejected a weighted scoring model once, and he was right to: an opaque
number nobody can read drifts somewhere nobody asked for. So this writes
sentences he can read, argue with, and edit by hand. The editorial pass
reads the file, not the votes.

Run before each editorial pass.
"""
import json, os, re, collections, datetime

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VOTES = os.path.join(REPO, "feedback", "votes.jsonl")
OUT = os.path.join(REPO, "config", "interests.md")

STOP = set("""the a an and or of to in for on with from this that these those is
are was were be been it its as at by about into over after new how why what
your you his her their our we i they them he she more most just than then so
not no yes can will would could should may might must one two three first
last next now today week year years day days time big small good best better
up down out off who whom which when where while all any both each few other
some such only own same very s t don now d ll m o re ve y""".split())


def words(t):
    return [w for w in re.findall(r"[a-z][a-z0-9'\-]{2,}", t.lower())
            if w not in STOP]


def load():
    """Last vote per id wins; 'clear' removes it."""
    latest = {}
    if os.path.exists(VOTES):
        with open(VOTES, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    v = json.loads(line)
                except json.JSONDecodeError:
                    continue
                latest[v["id"]] = v
    return [v for v in latest.values() if v.get("vote") in ("up", "down")]


def main():
    votes = load()
    ups = [v for v in votes if v["vote"] == "up"]
    downs = [v for v in votes if v["vote"] == "down"]

    L = ["# What he actually engages with", "",
         f"Generated by `execution/learn.py` on "
         f"{datetime.date.today().isoformat()} from "
         f"{len(votes)} rated items ({len(ups)} up, {len(downs)} down).", ""]

    if len(votes) < 5:
        L += ["**Not enough signal yet.** Fewer than 5 ratings. Do not change "
              "the brief's behaviour based on this file — keep the mix broad "
              "and keep §W (The Wildcard) deliberately strange. The point of "
              "§W is to generate this data in the first place.", ""]
        open(OUT, "w", encoding="utf-8").write("\n".join(L))
        print(f"interests.md — {len(votes)} votes, too few to act on")
        return

    sec_u = collections.Counter(v.get("section", "?") for v in ups)
    sec_d = collections.Counter(v.get("section", "?") for v in downs)
    L += ["## By section", "",
          "| section | up | down | read |", "|---|---|---|---|"]
    for sec in sorted(set(sec_u) | set(sec_d),
                      key=lambda s: -(sec_u[s] + sec_d[s])):
        u, d = sec_u[sec], sec_d[sec]
        if u and not d:
            read = "working — keep it"
        elif d and not u:
            read = "**not landing — cut it back**"
        elif u >= d * 2:
            read = "mostly working"
        elif d >= u * 2:
            read = "**mostly missing**"
        else:
            read = "mixed"
        L.append(f"| {sec} | {u} | {d} | {read} |")
    L.append("")

    wu = collections.Counter(w for v in ups for w in words(v.get("title", "")))
    wd = collections.Counter(w for v in downs for w in words(v.get("title", "")))
    liked = [w for w, c in wu.most_common(40) if c >= 2 and wd[w] < c]
    disliked = [w for w, c in wd.most_common(40) if c >= 2 and wu[w] < c]

    if liked:
        L += ["## Subjects he rates up", "",
              "Recurring words in things he liked — treat as direction, not a filter:",
              "", "> " + ", ".join(liked[:18]), ""]
    if disliked:
        L += ["## Subjects he rates down", "",
              "> " + ", ".join(disliked[:18]), "",
              "Give these less room. Do not remove them entirely unless a "
              "section's table row above says it is not landing at all.", ""]

    src_u = collections.Counter(v.get("source", "") for v in ups if v.get("source"))
    if src_u:
        L += ["## Sources worth more room", "",
              ", ".join(f"{s} ({c})" for s, c in src_u.most_common(8)), ""]

    L += ["## Standing rules", "",
          "- This is **direction, not a filter.** Never drop a whole topic "
          "because of a few downvotes.",
          "- **§W (The Wildcard) is exempt.** It must stay strange. Its job is "
          "to find interests that are not in this file yet, and it cannot do "
          "that if it is curated toward what already works.",
          "- Keep roughly one in five items outside everything above. A feed "
          "that only confirms what he already likes stops teaching him anything.",
          "- He can edit this file by hand. If he does, his words win.", ""]

    open(OUT, "w", encoding="utf-8").write("\n".join(L))
    print(f"interests.md — {len(ups)} up / {len(downs)} down across "
          f"{len(set(v.get('section','?') for v in votes))} sections")


if __name__ == "__main__":
    main()
